# Generated by Django 5.1.2 on 2024-10-28 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='loan',
            fields=[
                ('Name', models.CharField(max_length=10)),
                ('income', models.IntegerField(primary_key='Refno', serialize=False)),
                ('interest', models.FloatField()),
                ('duedate', models.DateField()),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
    ]
